### ISSUE TITLE
Call to Action Boxes - Font sizes

### ISSUE THREAD

**Issue by ElissaMarks** [kbrookes/siiteable#26]
There is no size difference in font sizes for the various options in any of the size options - all are just the one size

**Comment by kbrookes** [comment]
This is slightly tricky, but I'd welcome your feedback.

There's a set of default sizes for each heading and for paragraphs, across the choices of

XS
SM
MD
LG
XL

So if you chose XL for the title, and XL for the content section, and only used paragraphs in the content section, then they won't be the same size - the heading 2 title will be about 4rem and the P will be about 2.2rem.

When there's just one font control, like there is on the CTA - everything's proportional; the whole lot is set to XL, so headings, subheadings, paragraphs will all take on their proportional sizing for XL.

That said, I was already thinking about adding my standard font controls to the CTA for both the title and the content - but with the caveat that although it'll be available, I wouldn't use the font-weight control for the content sections, as you'll sometimes have multiple headings/paras within and may want to control the font weight directly in the editor.

Does that make sense?

**Comment by kbrookes** [comment]
That's been added to the title and content sections, although the above notes apply - the headings/paras are proportional.
