### ISSUE TITLE
Call to Action - Button

### ISSUE THREAD

**Issue by ElissaMarks** [kbrookes/siiteable#27]
Can there be padding around the CTA button, it butts right up to the copy above it. The padding is only for the cell, the button needs a bit of breathing space

**Comment by kbrookes** [comment]
ok!

**Comment by kbrookes** [comment]
There is now an option to add vertical padding to buttons.

Fully implemented for primary buttons, need to make some bigger changes to get secondary buttons up to date.

#48 Fixes and closes this issue.
