### ISSUE TITLE
Multi Cards - Buttons - 2nd Button

### ISSUE THREAD

**Issue by ElissaMarks** [kbrookes/siiteable#40]
In the Multi Cards, in the 'Content' area, you can add a button, and a secondary button, but only one button works - the Primary Button, not the secondary button.

I can use the Container tab section to create two buttons, so they are aligned for the whole container, not just the 'content' side of the Multi Card..

Same issue is that the two buttons touch each other also.

**Comment by kbrookes** [comment]
All fixed.
