### ISSUE TITLE
Header Main Title Alignment

### ISSUE THREAD

**Issue by ElissaMarks** [kbrookes/siiteable#41]
Every time I refresh, the heading title in the main page header is moving. I've had it set to 'align bottom' in the Customise area, however it keeps aligning elsewhere, firstly it was centered, now it's at the top...

**Comment by kbrookes** [comment]
Sorry, was working on this today.

There is now the option to set the default global setting for the header height and alignment in the customizer, but to then override both of those on the individual page. It's working now and pushed to Bamboo, so please test and let me know if you're still experiencing the issue.

**Comment by kbrookes** [comment]
All fixed.
