### ISSUE TITLE
Site 'updating' forever and eventually times out

### ISSUE THREAD

**Issue by ElissaMarks** [kbrookes/siiteable#76]
Hiya Kelsey

I've come across this a few times, when I hit update on my site, the 'updating' status spins for ages, and eventually doesn't update and I lose my changes...it's generally what makes me stop working on the site and take a break, and often trying to upload jpegs tells me they are too large and I need to make them smaller, yet they are smaller than the size it says it needs to be...am I doing soemthing that makes the updating not work?

**Comment by kbrookes** [comment]
I think this is also fixed - I've increased the resources available to the site, but let me know if it comes back.
